export interface Capsule {
  id: string;
  title: string;
  description: string; // User provided description
  mediaType: 'text' | 'image' | 'video' | 'audio';
  mediaBlob?: Blob; // The actual content
  mediaUrl?: string; // For previewing (created via URL.createObjectURL)
  unlockDate: string; // ISO String
  createdAt: string; // ISO String
  isLocked: boolean; // Runtime calculated status
  
  // AI Enhanced Metadata
  aiHint?: string; // A cryptic hint generated by Gemini about the content
  aiReflection?: string; // A generated reflection prompt for the future
}

export type ViewState = 'DASHBOARD' | 'CREATE' | 'VIEW_CAPSULE';

export interface CreateCapsuleFormData {
  title: string;
  description: string;
  unlockDate: string;
  mediaFile: File | null;
}
